#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <tag>"
  exit 1
fi

TAG=$1

git checkout main
git fetch --all
git reset --hard origin/main
git pull

mvn package -Dmaven.test.skip=true

docker build -t jellyfin-mp:$TAG .
docker rm -f jellyfin-mp
docker image prune -a -f
