version: '3'

services:
  jellyfin-mp:
    image: martin0313/jellyfin-mp:latest
    container_name: jellyfin-mp
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      DATABASE_URL: mysql:3306
      DATABASE_USER: jellyfinmp_user
      DATABASE_PASS: jellyfinmp_password
      BARK_SERVER: https://bark.changeme.com
      BARK_DEVICE: changeme_bark_device_id
      JELLYFIN_SERVER_URL: https://jellyfin.changeme.com
      JELLYFIN_ADMIN: changeme_jellyfin_user_id
      JELLYFIN_TOKEN: changeme_jellyfin_token
      MP_APP_ID: changeme_app_id
      MP_APP_SECRET: changeme_app_secret
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    privileged: true
    command: 
      mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: jellyfinmp
      MYSQL_USER: jellyfinmp_user
      MYSQL_PASSWORD: jellyfinmp_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data/data:/var/lib/mysql
      - ./mysql_data/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql_data/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  bark-server:
    image: finab/bark-server
    container_name: bark-server
    restart: unless-stopped
    volumes:
      - ./bark_data:/data
    ports:
      - "58080:8080"
